version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./app
    #       target: /code/app
    #     - action: rebuild
    #       path: requirements.txt
